"""Add destination field to Parcel

Revision ID: fb6b238a9474
Revises: b9a958607adf
Create Date: 2025-06-29 16:45:05.768270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6b238a9474'
down_revision = 'b9a958607adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcel', schema=None) as batch_op:
        batch_op.drop_column('destination')

    # ### end Alembic commands ###
